import json

from readxml import __version__, parse


def test_version():
    assert __version__ == '0.1.0'


# Example XML from the Python documentation, which meets `simple` requirements.
example = '\n'.join((
    '<?xml version="1.0"?>',
    '<data>',
    '    <country name="Liechtenstein">',
    '        <rank>1</rank>',
    '        <year>2008</year>',
    '        <gdppc>141100</gdppc>',
    '        <neighbor name="Austria" direction="E"/>',
    '        <neighbor name="Switzerland" direction="W"/>',
    '    </country>',
    '    <country name="Singapore">',
    '        <rank>4</rank>',
    '        <year>2011</year>',
    '        <gdppc>59900</gdppc>',
    '        <neighbor name="Malaysia" direction="N"/>',
    '    </country>',
    '    <country name="Panama">',
    '        <rank>68</rank>',
    '        <year>2011</year>',
    '        <gdppc>13600</gdppc>',
    '        <neighbor name="Costa Rica" direction="W"/>',
    '        <neighbor name="Colombia" direction="E"/>',
    '    </country>',
    '</data>'
))


simple_output = '\n'.join((
    '{',
    '    "[country]": [',
    '        {',
    '            "name": "Liechtenstein",',
    '            "rank": 1,',
    '            "year": 2008,',
    '            "gdppc": 141100,',
    '            "[neighbor]": [',
    '                {',
    '                    "name": "Austria",',
    '                    "direction": "E"',
    '                },',
    '                {',
    '                    "name": "Switzerland",',
    '                    "direction": "W"',
    '                }',
    '            ]',
    '        },',
    '        {',
    '            "name": "Singapore",',
    '            "rank": 4,',
    '            "year": 2011,',
    '            "gdppc": 59900,',
    '            "neighbor": {',
    '                "name": "Malaysia",',
    '                "direction": "N"',
    '            }',
    '        },',
    '        {',
    '            "name": "Panama",',
    '            "rank": 68,',
    '            "year": 2011,',
    '            "gdppc": 13600,',
    '            "[neighbor]": [',
    '                {',
    '                    "name": "Costa Rica",',
    '                    "direction": "W"',
    '                },',
    '                {',
    '                    "name": "Colombia",',
    '                    "direction": "E"',
    '                }',
    '            ]',
    '        }',
    '    ]',
    '}',
))


build_output = '\n'.join((
    '{',
    '    "": "data",',
    '    "[[]]": [',
    '        {',
    '            "name": "Liechtenstein",',
    '            "": "country",',
    '            "[[]]": [',
    '                {',
    '                    "": "rank",',
    '                    "[[]]": [',
    '                        "1"',
    '                    ]',
    '                },',
    '                {',
    '                    "": "year",',
    '                    "[[]]": [',
    '                        "2008"',
    '                    ]',
    '                },',
    '                {',
    '                    "": "gdppc",',
    '                    "[[]]": [',
    '                        "141100"',
    '                    ]',
    '                },',
    '                {',
    '                    "name": "Austria",',
    '                    "direction": "E",',
    '                    "": "neighbor",',
    '                    "[[]]": []',
    '                },',
    '                {',
    '                    "name": "Switzerland",',
    '                    "direction": "W",',
    '                    "": "neighbor",',
    '                    "[[]]": []',
    '                }',
    '            ]',
    '        },',
    '        {',
    '            "name": "Singapore",',
    '            "": "country",',
    '            "[[]]": [',
    '                {',
    '                    "": "rank",',
    '                    "[[]]": [',
    '                        "4"',
    '                    ]',
    '                },',
    '                {',
    '                    "": "year",',
    '                    "[[]]": [',
    '                        "2011"',
    '                    ]',
    '                },',
    '                {',
    '                    "": "gdppc",',
    '                    "[[]]": [',
    '                        "59900"',
    '                    ]',
    '                },',
    '                {',
    '                    "name": "Malaysia",',
    '                    "direction": "N",',
    '                    "": "neighbor",',
    '                    "[[]]": []',
    '                }',
    '            ]',
    '        },',
    '        {',
    '            "name": "Panama",',
    '            "": "country",',
    '            "[[]]": [',
    '                {',
    '                    "": "rank",',
    '                    "[[]]": [',
    '                        "68"',
    '                    ]',
    '                },',
    '                {',
    '                    "": "year",',
    '                    "[[]]": [',
    '                        "2011"',
    '                    ]',
    '                },',
    '                {',
    '                    "": "gdppc",',
    '                    "[[]]": [',
    '                        "13600"',
    '                    ]',
    '                },',
    '                {',
    '                    "name": "Costa Rica",',
    '                    "direction": "W",',
    '                    "": "neighbor",',
    '                    "[[]]": []',
    '                },',
    '                {',
    '                    "name": "Colombia",',
    '                    "direction": "E",',
    '                    "": "neighbor",',
    '                    "[[]]": []',
    '                }',
    '            ]',
    '        }',
    '    ]',
    '}',
))


def test_simple():
    assert json.dumps(parse(example, 'simple'), indent=4) == simple_output


def test_build():
    assert json.dumps(parse(example), indent=4) == build_output
